services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    container_name: sqlserver
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=Password123!"
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Password123!" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - cash-manager-network
    
  banking-api:
    image: banking-api
    build:
      context: .
      dockerfile: CashManager.Banking/CashManager.Banking.Api/Dockerfile
    container_name: banking-api
    ports:
      - "5000:80"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - cash-manager-network

  consumer-api:
    image: consumer-api
    build:
      context: .
      dockerfile: CashManager.Consumer/CashManager.Consumer.Api/Dockerfile
    container_name: consumer-api
    ports:
      - "5001:80"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - cash-manager-network

  banking-client:
    image: banking-client
    build:
      context: .
      dockerfile: cashmanager-banking-web/Dockerfile
    container_name: banking-client
    ports:
      - "3000:3000"
    depends_on:
      - banking-api
    networks:
      - cash-manager-network

  # consumer-client:
  #   image: consumer-client
  #   build:
  #     context: .
  #     dockerfile: cashmanagerapp/Dockerfile
  #   container_name: consumer-client
  #   ports:
  #     - "3001:8080"
  #   depends_on:
  #     - consumer-api
  #   networks:
  #     - cash-manager-network

volumes:
  sqlserver_data:

networks:
  cash-manager-network:
    driver: bridge